<?php

namespace CarBundle\Repository;

/**
 * CarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param string|null $searchTerm
     *
     * @return array
     */
    public function findCarsWithDetails($searchTerm = null)
    {
        $qb = $this->createQueryBuilder('c');
        $qb->select('c, make, model');
        $qb->join('c.make', 'make');
        $qb->join('c.model', 'model');

        if ($searchTerm !== null && $searchTerm !== '') {
            $qb->andWhere('make.name LIKE :term OR model.name LIKE :term');
            $qb->setParameter('term', '%'.$searchTerm.'%');
        }

        return $qb->getQuery()->getResult();
    }

    public function findCarWithDetailsWithId($id)
    {
        $qb = $this->createQueryBuilder('c');
        $qb->select('c, make, model');
        $qb->join('c.make', 'make');
        $qb->join('c.model', 'model');
        $qb->where('c.id = :id');
        $qb->setParameter('id', $id);

        return $qb->getQuery()->getOneOrNullResult();
    }

}
